### ISSUE TITLE
A lot of .cmd files missing during script run

### ISSUE THREAD

**Issue by runlevel-4** [fikinoob/SysUnlock#1]
So I assume that the "assets" you are referring to are the cmd scripts that get called throughout your main script.  I did not download the assets, so all throughout the script I was getting (scriptname).cmd was not found.  But also little cosmetic things like the 'msg' command are not recognized as internal commands.  I would recommend using the **echo** command instead.  Also at the very beginning of your scripts, I would add **@echo off**.  This makes it cleaner and strips the directories and things :)

**Comment by fikinoob** [comment]
Fixed
